name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
  args: ^2.0.0
  mongo_dart: ^0.7.4
  shelf: ^1.1.0
  shelf_plus: ^1.2.1
  shelf_router: ^1.0.0

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
